#!/usr/bin/env python3
"""QuarterMaster/M semantic-version synchronizer.

VERSION uses MAJOR.MINOR.PATCH. `--bump-patch` increments PATCH.
"""
from __future__ import annotations
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION_RE = re.compile(r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$")


def read_version() -> str:
    value = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    if not VERSION_RE.fullmatch(value):
        raise SystemExit(f"Invalid VERSION {value!r}; expected MAJOR.MINOR.PATCH")
    return value


def write_json(path: Path, version: str) -> None:
    data = json.loads(path.read_text(encoding="utf-8"))
    data["version"] = version
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def write_package_lock(path: Path, version: str) -> None:
    if not path.exists():
        return
    data = json.loads(path.read_text(encoding="utf-8"))
    data["version"] = version
    root_package = data.get("packages", {}).get("")
    if isinstance(root_package, dict):
        root_package["version"] = version
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def replace_cargo_version(path: Path, version: str) -> None:
    text = path.read_text(encoding="utf-8")
    text, count = re.subn(r'(?m)^version\s*=\s*"[^"]+"', f'version = "{version}"', text, count=1)
    if count != 1:
        raise SystemExit(f"Could not update package version in {path}")
    path.write_text(text, encoding="utf-8")


def sync(version: str) -> None:
    (ROOT / "VERSION").write_text(version + "\n", encoding="utf-8")
    write_json(ROOT / "package.json", version)
    write_package_lock(ROOT / "package-lock.json", version)
    write_json(ROOT / "src-tauri" / "tauri.conf.json", version)
    replace_cargo_version(ROOT / "src-tauri" / "Cargo.toml", version)
    (ROOT / "src" / "version.ts").write_text(
        '// Generated by scripts/version.py. Do not edit directly.\n'
        f'export const APP_VERSION = "{version}";\n', encoding="utf-8")
    (ROOT / "src-tauri" / "src" / "version.rs").write_text(
        '// Generated by scripts/version.py. Do not edit directly.\n'
        f'pub const APP_VERSION: &str = "{version}";\n', encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    bump_group = parser.add_mutually_exclusive_group()
    bump_group.add_argument("--bump-patch", action="store_true")
    bump_group.add_argument(
        "--bump-build",
        action="store_true",
        help="Legacy alias for --bump-patch",
    )
    parser.add_argument("--set", dest="set_version")
    args = parser.parse_args()
    version = args.set_version or read_version()
    if args.bump_patch or args.bump_build:
        major, minor, patch = map(int, VERSION_RE.fullmatch(version).groups())
        version = f"{major}.{minor}.{patch + 1}"
    if not VERSION_RE.fullmatch(version):
        raise SystemExit("Version must use MAJOR.MINOR.PATCH")
    sync(version)
    print(version)

if __name__ == "__main__":
    main()
